apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  destination:
    namespace: sample
    server: 'https://kubernetes.default.svc'
  source:
    path: 'k8s'
    repoURL: 'https://github.com/justduynguyen/sample-project.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
