apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-cert
  namespace: registry
spec:
  secretName: sample-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sample.s1.getsoft.vn
  dnsNames:
  - sample.s1.getsoft.vn
